name: hellow workflow 

on:
    # push:
    #     branches: main
    workflow_dispatch:

jobs:

    greet:
        runs-on: ubuntu-latest
        steps:
            - name: greet user
              run: echo "hellow dosto"

            - name: greet current user
              run: echo "hellow $USER"

    
    details:
        runs-on: ubuntu-latest
        steps:
            - name: get python version && docker version 
              run: docker --version && python3 --version 
                
